php -f hm/dohm.php OR1A1
php -f hm/dohm.php OR1A2
php -f hm/dohm.php OR1B1
php -f hm/dohm.php OR1C1
php -f hm/dohm.php OR1D2
php -f hm/dohm.php OR1D4
php -f hm/dohm.php OR1D5
php -f hm/dohm.php OR1E1
php -f hm/dohm.php OR1E2
php -f hm/dohm.php OR1E3
php -f hm/dohm.php OR1F1
php -f hm/dohm.php OR1F2
php -f hm/dohm.php OR1F12
php -f hm/dohm.php OR1G1
php -f hm/dohm.php OR1I1
php -f hm/dohm.php OR1J1
php -f hm/dohm.php OR1J2
php -f hm/dohm.php OR1J4
php -f hm/dohm.php OR1K1
php -f hm/dohm.php OR1L1
php -f hm/dohm.php OR1L3
php -f hm/dohm.php OR1L4
php -f hm/dohm.php OR1L6
php -f hm/dohm.php OR1L8
php -f hm/dohm.php OR1M1
php -f hm/dohm.php OR1N1
php -f hm/dohm.php OR1N2
php -f hm/dohm.php OR1Q1
php -f hm/dohm.php OR1S1
php -f hm/dohm.php OR1S2