php -f hm/dohm.php OR7A2
php -f hm/dohm.php OR7A5
php -f hm/dohm.php OR7A10
php -f hm/dohm.php OR7A17
php -f hm/dohm.php OR7C1
php -f hm/dohm.php OR7C2
php -f hm/dohm.php OR7D2
php -f hm/dohm.php OR7D4
php -f hm/dohm.php OR7E24
php -f hm/dohm.php OR7G1
php -f hm/dohm.php OR7G2
php -f hm/dohm.php OR7G3