php -f hm/dohm.php OR8A1
php -f hm/dohm.php OR8B2
php -f hm/dohm.php OR8B3
php -f hm/dohm.php OR8B4
php -f hm/dohm.php OR8B8
php -f hm/dohm.php OR8B12
php -f hm/dohm.php OR8D1
php -f hm/dohm.php OR8D2
php -f hm/dohm.php OR8D4
php -f hm/dohm.php OR8G1
php -f hm/dohm.php OR8G2
php -f hm/dohm.php OR8G5
php -f hm/dohm.php OR8H1
php -f hm/dohm.php OR8H2
php -f hm/dohm.php OR8H3
php -f hm/dohm.php OR8I2
php -f hm/dohm.php OR8J1
php -f hm/dohm.php OR8J3
php -f hm/dohm.php OR8K1
php -f hm/dohm.php OR8K3
php -f hm/dohm.php OR8K5
php -f hm/dohm.php OR8S1
php -f hm/dohm.php OR8U1
php -f hm/dohm.php OR8U8
