php -f hm/dohm.php OR9A2
php -f hm/dohm.php OR9A4
php -f hm/dohm.php OR9G1
php -f hm/dohm.php OR9G4
php -f hm/dohm.php OR9G9
php -f hm/dohm.php OR9I1
php -f hm/dohm.php OR9K2
php -f hm/dohm.php OR9Q1
php -f hm/dohm.php OR9Q2
